/**
 * @file turbo_peer_connection.h
 * @brief High-level WebRTC Peer Connection API
 *
 * simple facade that orchestrates ICE, DataChannels, Media, and SDP.
 */

#ifndef TURBO_PEER_CONNECTION_H
#define TURBO_PEER_CONNECTION_H

#include "turbo_media_engine.h"
#include "turbo_datachannel.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct turbo_peer_connection_s turbo_peer_connection_t;

typedef enum {
    TURBO_PEER_STATE_NEW,
    TURBO_PEER_STATE_CONNECTING,
    TURBO_PEER_STATE_CONNECTED,
    TURBO_PEER_STATE_DISCONNECTED,
    TURBO_PEER_STATE_FAILED,
    TURBO_PEER_STATE_CLOSED
} turbo_peer_state_t;

typedef struct {
    void (*on_state_change)(turbo_peer_connection_t *pc, turbo_peer_state_t state, void *user_data);
    void (*on_track)(turbo_peer_connection_t *pc, turbo_media_track_t *track, void *user_data);
    void (*on_datachannel)(turbo_peer_connection_t *pc, turbo_dc_channel_t *channel, void *user_data);
    
    /* SDP/Signaling callbacks */
    void (*on_ice_candidate)(turbo_peer_connection_t *pc, const char *candidate, void *user_data);
} turbo_peer_callbacks_t;

typedef struct {
    /* ICE Configuration */
    const char **stun_servers;
    int stun_server_count;
    const char **turn_servers; /* format: "turn:user:pass@host:port" */
    int turn_server_count;
    int allow_loopback;
    int disable_datachannel;
    
    /* Options */
    void *user_data;
} turbo_peer_config_t;

/**
 * Create a new PeerConnection
 */
TURBO_MEDIA_API turbo_peer_connection_t *turbo_peer_connection_create(
    const turbo_peer_config_t *config,
    const turbo_peer_callbacks_t *callbacks
);


/**
 * Destroy PeerConnection
 */
TURBO_MEDIA_API void turbo_peer_connection_destroy(turbo_peer_connection_t *pc);

/**
 * Add a media track
 */
TURBO_MEDIA_API turbo_media_track_t *turbo_peer_connection_add_track(
    turbo_peer_connection_t *pc,
    turbo_rtc_media_track_type_t type,
    turbo_media_direction_t direction
);

/**
 * Add a media track with explicit codec and media parameters.
 */
TURBO_MEDIA_API turbo_media_track_t *turbo_peer_connection_add_track_ex(
    turbo_peer_connection_t *pc,
    const turbo_media_track_config_t *config
);

/**
 * Add a DataChannel
 */
TURBO_MEDIA_API turbo_dc_channel_t *turbo_peer_connection_create_datachannel(
    turbo_peer_connection_t *pc,
    const char *label,
    const turbo_dc_channel_config_t *config
);

/**
 * Create SDP Offer
 * @param sdp_out Buffer to store SDP
 * @param max_len Size of buffer
 * @return 0 on success
 */
TURBO_MEDIA_API int turbo_peer_connection_create_offer(
    turbo_peer_connection_t *pc,
    char *sdp_out,
    size_t max_len
);

/**
 * Start a new ICE generation while retaining gathered local candidates.
 *
 * Call turbo_peer_connection_create_offer() after this succeeds and signal
 * that offer to the remote peer. The existing DTLS/SRTP session is retained
 * and is rebound to the newly selected ICE pair.
 *
 * @return 0 on success, negative on invalid state or allocation failure
 */
TURBO_MEDIA_API int turbo_peer_connection_restart_ice(
    turbo_peer_connection_t *pc
);

/**
 * Create SDP Answer (after setting remote description)
 */
TURBO_MEDIA_API int turbo_peer_connection_create_answer(
    turbo_peer_connection_t *pc,
    char *sdp_out,
    size_t max_len
);

/**
 * Set Remote Description (SDP)
 * @param type "offer" or "answer"
 * @param sdp SDP string
 */
TURBO_MEDIA_API int turbo_peer_connection_set_remote_description(
    turbo_peer_connection_t *pc,
    const char *type,
    const char *sdp
);

/**
 * Add remote ICE candidate
 */
TURBO_MEDIA_API int turbo_peer_connection_add_ice_candidate(
    turbo_peer_connection_t *pc,
    const char *candidate
);

/**
 * Apply a WHIP/WHEP trickle ICE SDP fragment.
 *
 * The fragment may contain candidates only, or a complete new ICE
 * ufrag/password pair followed by candidates. A changed credential pair starts
 * a remote-initiated ICE restart while retaining the negotiated DTLS/SRTP
 * session.
 *
 * @return 1 if a new ICE generation was applied, 0 for candidate-only update,
 *         or a negative value for malformed input or invalid state
 */
TURBO_MEDIA_API int turbo_peer_connection_apply_remote_ice_sdpfrag(
    turbo_peer_connection_t *pc,
    const char *sdpfrag,
    size_t sdpfrag_len
);

/**
 * Build the local ICE SDP fragment for the current generation.
 *
 * @return generated byte count, or a negative value on failure
 */
TURBO_MEDIA_API int turbo_peer_connection_create_local_ice_sdpfrag(
    turbo_peer_connection_t *pc,
    char *sdpfrag_out,
    size_t max_len
);

/**
 * Drive the peer connection's ICE, DTLS, DataChannel, and media timers once
 * without blocking.
 *
 * Call this regularly from applications that manage their own loop so queued
 * transport work, socket I/O, RTCP, TWCC, and jitter-buffer delivery can make
 * progress. Callers must not drive the returned internal media context's timers
 * separately.
 */
TURBO_MEDIA_API void turbo_peer_connection_poll(turbo_peer_connection_t *pc);

/**
 * Get internal context handles (for advanced usage)
 */
TURBO_MEDIA_API turbo_media_context_t *turbo_peer_connection_get_media_context(turbo_peer_connection_t *pc);
TURBO_MEDIA_API turbo_dc_peer_t *turbo_peer_connection_get_dc_peer(turbo_peer_connection_t *pc);

#ifdef __cplusplus
}
#endif

#endif /* TURBO_PEER_CONNECTION_H */
