# Project-wide Gradle settings
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true

# AndroidX package structure
android.useAndroidX=true
android.enableJetifier=true

# Kotlin code style
kotlin.code.style=official

# Enable R8 full mode
android.enableR8.fullMode=true

# Enable build cache
android.enableBuildCache=true

# NDK settings
android.ndkVersion=25.2.9519653

# Prefab
android.prefabVersion=2.0.0
